/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polinomHesaplamaGui;

import javax.tools.Diagnostic;

/**
 *
 * @author gunes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    public boolean usKontrol(int[][] degerler){
        int fark=degerler[0][1]-degerler[1][1];
        int farkKontrol;
        for(int i=0;i<polinom.getAdet()-1;i++){
            farkKontrol=degerler[i][1]-degerler[i+1][1];
            if(fark!=farkKontrol||degerler[i][1]==0)
                return false;
        }
        return true;
    }
    //Polinom sınıfından bağlı liste oluşturmak için nesne
    Polinom polinom = new Polinom();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Polinom");

        jTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("X değeri");

        jTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jLabel3.setText("Polinom :");

        jLabel4.setText("Polinom sonucu : ");

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton2.setText("Ekle");
        jButton2.setName(""); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton3.setText("Sıfırla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Üs tam mı?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Üs tam :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(158, 158, 158)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //polinomun hesaplanıp GUI üzerinde gösterilmesi için buton kodları
        if (jTextField2.getText() != "") {
            int toplam = 0;
            int xDegeri = Integer.parseInt(jTextField2.getText());
            int[][] degerler = polinom.degerler();
            for (int i = 0; i < polinom.getAdet(); i++) {
//                System.out.println(degerler[i][0] + " " + degerler[i][1]);
                toplam += degerler[i][0]*(Math.pow(xDegeri, degerler[i][1]));
            }
            jLabel4.setText("Polinom sonucu : " + toplam);
        } else {
            System.out.println("X değeri girin");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Polinoma yeni düğüm eklemek için buton komutları
        String plnm, a = "";
        int katSayi = 1, us = 1;
        boolean sira = true;
        //polinome yeni eklenecek değerin belirlenen maksimum uzunluktan fazla olması ör:[-2x^3] 5 karakterli
        if (jTextField1.getText().length() > 5) {
            jTextField1.setText("Çok fazla değer girdiniz!!");
        } //girilen değer belirlenen aralıkta ama kat sayısı yoksa çalışacak kısım
        else if (jTextField1.getText().length() == 4 && jTextField1.getText().charAt(0) == '-' || jTextField1.getText().charAt(0) == '+') {
            if (jTextField1.getText().charAt(0) == '-') {
                katSayi = -1;
                a += jTextField1.getText().charAt(3);
                us = Integer.parseInt(a);
            } else if (jTextField1.getText().charAt(0) == '+') {
                katSayi = 1;
                a += jTextField1.getText().charAt(3);
                us = Integer.parseInt(a);
            }
        } //girilen değer kat sayısız ve işaretsiz ise çalışacak kısım
        else if (jTextField1.getText().length() == 3) {
            if (jTextField1.getText().charAt(0) == 'x' || jTextField1.getText().charAt(0) == 'X') {
                katSayi = 1;
                a += jTextField1.getText().charAt(2);
                us = Integer.parseInt(a);
            }

        } 
        else if(jTextField1.getText().length()==2&&jTextField1.getText().charAt(0)=='-'){
            if(jTextField1.getText().charAt(1)=='x'||jTextField1.getText().charAt(1)=='X')
            {
                katSayi=-1;
                us=1;
            }else if(jTextField1.getText().charAt(1)>='1'&&jTextField1.getText().charAt(1)<='9'){
                a += jTextField1.getText().charAt(1);
                katSayi=Integer.parseInt(a)*-1;
                us=1;
            }
        }else if(jTextField1.getText().length()==2&&jTextField1.getText().charAt(0)=='+'){
            if(jTextField1.getText().charAt(1)=='x'||jTextField1.getText().charAt(1)=='X')
            {
                katSayi=1;
                us=1;
            }else if(jTextField1.getText().charAt(1)>='1'&&jTextField1.getText().charAt(1)<='9'){
                a += jTextField1.getText().charAt(1);
                katSayi=Integer.parseInt(a);
                us=1;
            }
        }
        else if(jTextField1.getText().length()==1&&jTextField1.getText().charAt(0)>='1'&&jTextField1.getText().charAt(0)<='9'){
            a += jTextField1.getText().charAt(0);
            katSayi=Integer.parseInt(a);
            us=0;
            
        }
            //girilen değerin<=5 karakter olduğu spesifik olmayan tüm durumlar için
        else {
            plnm = jTextField1.getText();
            a = "";
            for (int i = 0; i < plnm.length(); i++) {
                if (plnm.charAt(i) >= '1' && plnm.charAt(i) <= '9') {
                    if (sira == true) {
                        a += plnm.charAt(i);
                        katSayi = Integer.parseInt(a);
                        a = "";
                        sira = false;
                    } else {
                        a += plnm.charAt(i);
                        us = Integer.parseInt(a);
                        a = "";
                        sira = true;
                    }
                } else if (plnm.charAt(i) == '-') {
                    if (sira == true) {
                        a += plnm.charAt(i + 1);
                        katSayi = (Integer.parseInt(a) * -1);
                        a = "";
                        sira = false;
                    } else {
                        a += plnm.charAt(i + 1);
                        us = (Integer.parseInt(a) * -1);
                        a = "";
                        sira = true;
                    }
                    i++;
                } else if (plnm.charAt(i) == '+') {
                    if (sira == true) {
                        a += plnm.charAt(i + 1);
                        katSayi = Integer.parseInt(a);
                        a = "";
                        sira = false;
                    } else {
                        a += plnm.charAt(i + 1);
                        us = Integer.parseInt(a);
                        a = "";
                        sira = true;
                    }
                    i++;
                }

            }
        }
        //yeni değer listeye eklendikten sonra çalışan komutlar
//        System.out.println(katSayi+" "+us);
        polinom.add(katSayi, us);
        jLabel3.setText(polinom.yaz());
        jTextField1.setText("");
        sira = true;
        a = "";


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jLabel3.setText("Polinom :");
        jLabel4.setText("Polinom sonucu : ");
        polinom.listeSifirla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean usTamMi;
        usTamMi=usKontrol(polinom.degerler());
        jLabel5.setText(jLabel5.getText()+" "+usTamMi);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
